spring:
  datasource:
    url: jdbc:postgresql://hapi-fhir-postgres:5432/hapi
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
      hibernate.search.enabled: false

hapi:
  fhir:
    # Recreate the Postgres volume after changing fhir_version or ID strategy.
    fhir_version: R5
    server_id_strategy: UUID
    client_id_strategy: ANY
    allow_cascading_deletes: true
    openapi_enabled: true
    subscription:
      resthook_enabled: true
    cors:
      allow_Credentials: true
      allowed_origin:
        - http://localhost:8080
        - http://localhost:8480
